server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: user
    password: 1234
  jpa:
    properties:
      hibernate:
        default_schema: demo
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true


