CREATE SCHEMA IF NOT EXISTS demo;

CREATE TABLE IF NOT EXISTS demo.USERS (
    ID BIGSERIAL PRIMARY KEY ,
    NICKNAME VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS demo.MESSAGES (
    ID BIGSERIAL PRIMARY KEY ,
    MESSAGE VARCHAR(50) UNIQUE NOT NULL,
    USER_ID BIGINT NOT NULL,
    CREATED_AT timestamp,
    FOREIGN KEY (USER_ID) REFERENCES demo.USERS(ID)
);

CREATE TABLE IF NOT EXISTS demo.USER_FOLLOWS (
    USER_ID BIGINT NOT NULL,
    FOLLOW_USER_ID BIGINT,
    PRIMARY KEY (USER_ID, FOLLOW_USER_ID),
    FOREIGN KEY (USER_ID) REFERENCES demo.USERS (ID),
    FOREIGN KEY (FOLLOW_USER_ID) REFERENCES demo.USERS (ID)
)

